title: Zero to a One: My journey from a noob to competent programmer
author: imRanDan (Danyal Imran)
email: dan.imran97@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is the start of my journey. I graduated with a BA in General Arts and have been drifting around not knowing what I wanted to do with my career. I have spent this time to truly reflect and decided that Coding was something I could do.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
